### ISSUE TITLE
Cannot get it to work :(

### ISSUE THREAD

**Issue by xircon** [emanuelep57/Qminimize#1]
```
qminimize -u
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/ipc.py", line 118, in unpack
    assert len(data) >= HDRLEN
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xircon/.local/bin/qminimize", line 97, in <module>
    main()
  File "/home/xircon/.local/bin/qminimize", line 84, in main
    string = minimized_windows_list(minimized_icons)
  File "/home/xircon/.local/bin/qminimize", line 68, in minimized_windows_list
    if c.window[i].info()["minimized"] is True:
  File "/usr/lib/python3.10/site-packages/libqtile/command/client.py", line 227, in __getattr__
    if not self._command.has_command(self._current_node, name):
  File "/usr/lib/python3.10/site-packages/libqtile/command/interface.py", line 251, in has_command
    commands = self.execute(cmd_call, (), {})
  File "/usr/lib/python3.10/site-packages/libqtile/command/interface.py", line 225, in execute
    status, result = self._client.send((call.parent.selectors, call.name, args, kwargs))
  File "/usr/lib/python3.10/site-packages/libqtile/ipc.py", line 161, in send
    return asyncio.run(self.async_send(msg))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/libqtile/ipc.py", line 189, in async_send
    data, _ = _IPC.unpack(read_data, is_json=self.is_json)
  File "/usr/lib/python3.10/site-packages/libqtile/ipc.py", line 123, in unpack
    raise IPCError("error reading reply! (probably the socket was disconnected)") from e
libqtile.ipc.IPCError: error reading reply! (probably the socket was disconnected)
```
Any ideas?  EndeavourOS (Arch with an installer),  qtile 0.19.1.dev10+gda78ea40

**Comment by emanuelep57** [comment]
This is a known issue with qtile, I talked to one of the dev and he said
they are going to solve it. Anyway temporary you can avoid this issue by
removing the tray widget from the bar.

**Comment by emanuelep57** [comment]
The issue was fixed by qtile :)
