### ISSUE TITLE
error with multiple monitors

### ISSUE THREAD

**Issue by bentobit8** [emanuelep57/Qminimize#2]
it show this error with multiple monitors;

```
Traceback (most recent call last):
  File "/home/ben/.local/bin/Qminimize", line 97, in <module>
    main()
  File "/home/ben/.local/bin/Qminimize", line 84, in main
    string = minimized_windows_list(minimized_icons)
  File "/home/ben/.local/bin/Qminimize", line 68, in minimized_windows_list
    if c.window[i].info()["minimized"] is True:
KeyError: 'minimized'
```

there is no error when unplugged external monitor and reboot.

**Comment by bentobit8** [comment]
i've found the solution;
line 35 change 
```python
for i in range (0, len("/usr/share/applications"), 1):
```
to
```python
for i in range (0, len([item for item in os.listdir("/usr/share/applications")]), 1):
```
and put this ontop
```python
import os
```

**Comment by emanuelep57** [comment]
I am sorry for the late answer, I moved and had no computer with me. Do you mind merging a pull request?

**Comment by emanuelep57** [comment]
Fixed this, thanks
